# Generated by Django 6.0.6 on 2026-06-26 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('avance_pct', models.PositiveSmallIntegerField(default=0, verbose_name='Avance (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('brecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones', to='analytics.brecha')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='workers.trabajador')),
            ],
            options={
                'verbose_name': 'Asignación de capacitación',
                'verbose_name_plural': 'Asignaciones de capacitación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('asistio', models.BooleanField(default=True, verbose_name='Asistió')),
                ('observacion', models.CharField(blank=True, default='', max_length=240, verbose_name='Observación')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='training.asignacioncapacitacion')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('area_tema', models.CharField(max_length=120, verbose_name='Área temática')),
                ('material_url', models.URLField(blank=True, default='', verbose_name='URL del material')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de capacitación',
                'verbose_name_plural': 'Planes de capacitación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='asignacioncapacitacion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='training.plancapacitacion'),
        ),
        migrations.AddConstraint(
            model_name='asignacioncapacitacion',
            constraint=models.UniqueConstraint(fields=('plan', 'trabajador'), name='uniq_plan_trabajador'),
        ),
    ]
