# Generated by Django 6.0.6 on 2026-06-20 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_usuarios', 'Ver usuarios'), ('gestionar_usuarios', 'Crear, editar, activar y resetear usuarios'), ('ver_roles', 'Ver roles'), ('gestionar_roles', 'Crear, editar y activar roles'), ('ver_trabajadores', 'Ver trabajadores'), ('gestionar_trabajadores', 'Crear, editar y administrar trabajadores'), ('ver_evaluaciones', 'Ver evaluaciones de competencias'), ('gestionar_evaluaciones', 'Crear, asignar y calificar evaluaciones'), ('ver_capacitaciones', 'Ver capacitaciones'), ('gestionar_capacitaciones', 'Registrar, asignar y dar seguimiento a capacitaciones'), ('ver_reportes', 'Ver reportes de cumplimiento'), ('gestionar_reportes', 'Generar y exportar reportes en PDF'), ('ver_bitacora', 'Consultar la bitácora del sistema')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RolPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='auth.group', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Perfil de rol',
                'verbose_name_plural': 'Perfiles de rol',
            },
        ),
    ]
