# Generated by Django 6.0.6 on 2026-06-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlacceso',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_usuarios', 'Ver usuarios'), ('gestionar_usuarios', 'Crear, editar, activar y resetear usuarios'), ('ver_roles', 'Ver roles'), ('gestionar_roles', 'Crear, editar y activar roles'), ('ver_trabajadores', 'Ver trabajadores'), ('gestionar_trabajadores', 'Crear, editar y administrar trabajadores'), ('ver_evaluaciones', 'Ver evaluaciones de competencias'), ('gestionar_evaluaciones', 'Crear, asignar y calificar evaluaciones'), ('ver_analytics', 'Ver diagnóstico de competencias y brechas'), ('gestionar_analytics', 'Procesar análisis y validar/descartar brechas'), ('ver_capacitaciones', 'Ver capacitaciones'), ('gestionar_capacitaciones', 'Registrar, asignar y dar seguimiento a capacitaciones'), ('ver_reportes', 'Ver reportes de cumplimiento'), ('gestionar_reportes', 'Generar y exportar reportes en PDF'), ('ver_bitacora', 'Consultar la bitácora del sistema')]},
        ),
    ]
