# Generated by Django 6.0.6 on 2026-06-26 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_tema', models.CharField(max_length=120, verbose_name='Área temática')),
                ('nivel_detectado', models.CharField(max_length=20, verbose_name='Nivel detectado')),
                ('descripcion', models.CharField(max_length=240, verbose_name='Descripción')),
                ('origen', models.CharField(default='analytics', max_length=20)),
                ('estado', models.CharField(choices=[('sugerida', 'Sugerida'), ('validada', 'Validada'), ('descartada', 'Descartada')], default='sugerida', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brechas', to='workers.trabajador')),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brechas_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brecha',
                'verbose_name_plural': 'Brechas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_tema', models.CharField(max_length=120, verbose_name='Área temática')),
                ('motivo', models.CharField(max_length=240, verbose_name='Motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('brecha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacion', to='analytics.brecha')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='NivelCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_tema', models.CharField(max_length=120, verbose_name='Área temática')),
                ('score', models.FloatField(default=0, verbose_name='Puntaje de competencia (%)')),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_competencia', to='workers.trabajador')),
            ],
            options={
                'verbose_name': 'Nivel de competencia',
                'verbose_name_plural': 'Niveles de competencia',
                'ordering': ['area_tema'],
                'constraints': [models.UniqueConstraint(fields=('trabajador', 'area_tema'), name='uniq_competencia_trab_area')],
            },
        ),
    ]
